### ISSUE TITLE
Error en la altura del parámetro levantar Z en Perfiles Vertex XL

### ISSUE THREAD

**Issue by Dainse** [Vertex3dPrinters/profiles#2]
El parámetro de Levantar Z (ZHOP) está con la configuración heredada de Mk3s y no se corresponde con la altura de la máquina por lo que a partir de 209mm desactiva levantar Z pudiendo provocar roces del nozzle contra las capas impresas. Es necesario ajustar ese parámetro a la altura real de la máquina teniendo en cuenta el margen de altura del que disponemos. 
![Error Zhop Perfil SuperSlicer](https://user-images.githubusercontent.com/39022365/121730945-9a9eeb00-caf0-11eb-9472-7c5de341619e.jpg)

**Comment by jfestrada** [comment]
The issue has been solved, thanks!!
